#include<iostream.h>
#include<conio.h>
void main(){
clrscr();
char al;
cout<<"\n\n\tEnter a alphabets:";
cin>>al;
clrscr();
cout<<"\n\n\t";
if(al=='A'){
cout<<al<<" aplhabet is vowel.";
}
else{
if(al=='a'){
cout<<al<<" this alphabet is vowel.";
}
else{

if(al=='E'){
cout<<al<<" this alphabet is vowel.";
}
else{

if(al=='e'){
cout<<al<<" this alphabet is vowel.";
}
else{

if(al=='I'){
cout<<al<<" this alphabet is vowel.";
}
else{

if(al=='i'){
cout<<al<<" this alphabet is vowel.";
}
else{

if(al=='O'){
cout<<al<<" this alphabet is vowel.";
}
else{

if(al=='o'){
cout<<al<<" this alphabet is vowel.";
}
else{

if(al=='U'){
cout<<al<<" this alphabet is vowel.";
}
else{

if(al=='u'){
cout<<al<<" this alphabet is vowel.";
}
else{
cout<<"This alphabet is not vowel.";
}

} // U if closing

}   //o if closing

}    // O if closing


}    //  i if closing

}     //I if closing

}   //   e if closing

}     //E if closing

}   // a if closing

}//A if closing
char cl2;
clrscr();
cout<<"Enter alphabet:";
cin>>cl2;
if( cl2=='A'|| cl2=='a'|| cl2=='E'|| cl2=='e'|| cl2=='I'|| cl2=='i'|| cl2=='O'|| cl2=='o'|| cl2=='U'|| cl2=='u'){
cout<<cl2<<" this alphabet is vowel";
}


getch();
}