#include<iostream.h>
#include<conio.h>
void main(){
clrscr();
int n;
cout<<"\n\n\tEnter a number:";
cin>>n;
clrscr();
cout<<"\n\n\t";
if(n>0){
cout<<"Your number is positive number.";
}
else{
if(n<0){
cout<<"Your number is negative.";
}
else{
cout<<"Your enter nubmer is Zero.";
}
}
clrscr();
//next prgram
int stay;
cout<<"\n\n\tNext program is starting....";
cin>>stay;
clrscr();
int n1,n2,n3;
cout<<"\n\n\t Enter number 1:";
cin>>n1;

getch();
}